global:
  cloud: others
  clusterName: homelab-k3s
  deploymentEnvironment: homelab
  storageClass: nfs-client

# SigNoz OTel Collector 엔드포인트 
# 같은 네임스페이스이므로 서비스명으로 접근
otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
otelInsecure: true

presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: false

# 호스트 메트릭 수집 설정
hostMetrics:
  collectionInterval: 60s
  scrapers:
    cpu:
      metrics:
        system.cpu.logical.count:
          enabled: true
        system.cpu.physical.count:
          enabled: true
        system.cpu.utilization:
          enabled: true
    load:
      enabled: true
    memory:
      enabled: true
    disk:
      enabled: true
    filesystem:
      enabled: true
    network:
      enabled: true

# Kubelet 메트릭 수집 설정  
kubeletMetrics:
  collectionInterval: 60s
  metrics:
    k8s.pod.cpu_request_utilization:
      enabled: true
    k8s.pod.memory_request_utilization:
      enabled: true
    k8s.pod.cpu_limit_utilization:
      enabled: true
    k8s.pod.memory_limit_utilization:
      enabled: true
    k8s.node.cpu.usage:
      enabled: true
    k8s.node.memory.usage:
      enabled: true