# values.yaml
nfs:
  server: 192.168.0.101  # NFS 서버 IP (필수)
  path: /srv/k8s         # NFS 공유 경로 (필수)
  mountOptions:
    - nfsvers=4     # NFS v4 지정

storageClass:
  name: nfs-client        # StorageClass 이름
  defaultClass: true
  archiveOnDelete: true   # PVC 삭제 시 archived-{name}으로 보관
  onDelete: delete        # PVC 삭제시 PV 삭제
  pathPattern: "${.PVC.namespace}/${.PVC.name}-${.PVC.uid}" # UID를 포함하여 완전한 고유성 보장
