---
- name: 홈랩 부팅 완료 Slack 알림 서비스 설정
  hosts: homelab
  become: yes

  tasks:
    - name: Slack 설정 확인
      debug:
        msg: "Slack Webhook URL이 설정되지 않아 Slack 알림 설정을 건너뜁니다."
      when: slack_webhook_url is not defined or slack_webhook_url == ""

    - name: curl 패키지 설치
      apt:
        name: curl
        state: present
        update_cache: yes
      when: slack_webhook_url is defined and slack_webhook_url != ""

    - name: 부팅 알림 스크립트 생성 (vars에서 webhook URL 삽입)
      template:
        src: ../files/homelab-boot-notify.sh.j2
        dest: /usr/local/bin/homelab-boot-notify.sh
        mode: '0755'
        owner: root
        group: root
      when: slack_webhook_url is defined and slack_webhook_url != ""

    - name: systemd 서비스 파일 복사
      copy:
        src: ../files/homelab-boot-notify.service
        dest: /etc/systemd/system/homelab-boot-notify.service
        mode: '0644'
        owner: root
        group: root
      when: slack_webhook_url is defined and slack_webhook_url != ""

    - name: systemd 데몬 리로드
      systemd:
        daemon_reload: yes
      when: slack_webhook_url is defined and slack_webhook_url != ""

    - name: 부팅 알림 서비스 활성화
      systemd:
        name: homelab-boot-notify
        enabled: yes
        state: stopped
      when: slack_webhook_url is defined and slack_webhook_url != ""

    - name: Slack 설정 완료 메시지
      debug:
        msg: "✅ Slack 부팅 알림 서비스가 설정되었습니다. 다음 부팅시부터 알림이 전송됩니다."
      when: slack_webhook_url is defined and slack_webhook_url != ""