all:
  children:
    homelab:
      hosts:
        ubuntu-server:
          ansible_host: "{{ target_ip }}"
          ansible_user: "{{ target_username }}"
          ansible_password: "{{ target_password }}"
          ansible_become_password: "{{ target_password }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python3