#!/usr/bin/env just --justfile

# Kubernetes 리소스 관리
# 사용법: just <command>

# 도움말 표시
_default:
    @just --list

# Kubeflow 관리
mod kubeflow 'applications/kubeflow'

# ArgoCd 관리
mod n8n 'applications/argo'